---
driver:
  name: vagrant
  box: ubuntu/wily64

provisioner:
  name: chef_solo

platforms:
  - name: master
    driver_config:
      network:
        - ["private_network", {ip: "192.168.40.10"}]
    run_list:
      - recipe[etcd]
      - recipe[kubernetes-install::master]
      - recipe[export-node::default]

  - name: node
    driver_config:
      network:
        - ["private_network", {ip: "192.168.40.11"}]
    run_list:
      - recipe[etcd]
      - recipe[kubernetes-install::node]
      - recipe[export-node::default]

suites:
  - name: cluster
    run_list: []
    attributes:
      etcd:
        addr: "0.0.0.0:4001"
        args: "-bind-addr=0.0.0.0:4001"
        url: "https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz"
        sha256: "b351d05f68d2a8f3fce2d4038f3ecf3408901ac2ec37240ff0043b4c989484f5"
      kubernetes:
        package: "https://github.com/kubernetes/kubernetes/releases/download/v1.1.8/kubernetes.tar.gz"
        masters: ["192.168.40.10"]
        nodes: ["192.168.40.11"]
