---
driver:
  name: vagrant
  box: ubuntu/wily64

provisioner:
  name: chef_zero

platforms:
  - name: master
    driver_config:
      network:
        - ["private_network", {ip: "192.168.40.10"}]
    run_list:
      - recipe[kubernetes-cluster::master]

  - name: node
    driver_config:
      network:
        - ["private_network", {ip: "192.168.40.11"}]
    run_list:
      - recipe[kubernetes-cluster::node]

suites:
  - name: cluster
    run_list: []
    attributes:
      kubernetes:
        masters: ["192.168.40.10"]
        nodes: ["192.168.40.11"]
